# functions to read/write level-1 networks

# .out file from snaq written by optTopRuns
"""
    readsnaqnetwork(output file)

Read the estimated network from a `.out` file generated by [`snaq!`](@ref).
The network score is read also, and can be accessed with the [`loglik`](@ref) function.
"""
function readsnaqnetwork(file::AbstractString)
    open(file) do s
        line = readline(s)
        line[1] == '(' ||
          error("output file $(file) does not contain a tree in the first line, instead it has $(line); or we had trouble finding ploglik.")
        # println("Estimated network from file $(file): $(line)")
        net = readnewick(line)
        # readTopologyUpdate is inadequate: would replace missing branch lengths, which are unidentifiable, by 1.0 values
        try
            vec = split(line,"loglik = ")
            loglik!(net, parse(Float64,vec[2]))
        catch e
            @warn "could not find the network score; the error was:"
            rethrow(e)
        end
        return net
    end
end


"""
    readallsnaqnetworks(outfile)

Read all of the optimal networks from a `.networks` file generated
by the [`snaq!`](@ref) function. The composite log-likelihood of each
network is also read and can be accessed individually with the
[`loglik`](@ref) function.
"""
function readallsnaqnetworks(outfile::String)::Vector{HybridNetwork}
	lines = [l for l in readlines(outfile) if occursin("with loglik", l)]
	nets = []
	for l in lines
		l1, l2 = split(l, ", with loglik ")
		n = readnewick(l1)
        if occursin("best network found", l2)
            l2 = split(l2, " (best network found")[1]
        end
		loglik!(n, parse(Float64, l2))
		push!(nets, n)
	end
	return nets
end
