# functions to read/write level-1 networks

# .out file from snaq written by optTopRuns
"""
    readsnaqnetwork(output file)

Read the estimated network from a `.out` file generated by [`snaq!`](@ref).
The network score is read also, and stored in the network's field `.loglik`.

Warning: despite the name "loglik", this score is only proportional
to the network's pseudo-deviance: the lower, the better.
Do NOT use this score to calculate an AIC or BIC (etc.) value.
"""
function readsnaqnetwork(file::AbstractString)
    open(file) do s
        line = readline(s)
        line[1] == '(' ||
          error("output file $(file) does not contain a tree in the first line, instead it has $(line); or we had trouble finding ploglik.")
        # println("Estimated network from file $(file): $(line)")
        net = readnewick(line)
        # readTopologyUpdate is inadequate: would replace missing branch lengths, which are unidentifiable, by 1.0 values
        try
            vec = split(line,"-Ploglik = ")
            loglik!(net, parse(Float64,vec[2]))
        catch e
            @warn "could not find the network score; the error was:"
            rethrow(e)
        end
        return net
    end
end
